version: '3.7'
services:
  zookeeper-1:
    image: zookeeper
    restart: always
    hostname: zookeeper-1
    logging:
      driver: "none"
    ports:
      - 2181:2181
    expose:
      - 2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
    entrypoint: |
      bash -c '
        /docker-entrypoint.sh zkServer.sh start-foreground'
  zookeeper-2:
    image: zookeeper
    restart: always
    hostname: zookeeper-2
    logging:
      driver: "none"
    ports:
      - 2182:2181
    expose:
      - 2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper-3:2888:3888
    entrypoint: |
      bash -c '
        /docker-entrypoint.sh zkServer.sh start-foreground'
    depends_on:
      - zookeeper-1
  zookeeper-3:
    image: zookeeper
    restart: always
    hostname: zookeeper-3
    logging:
      driver: "none"
    ports:
      - 2183:2181
    expose:
      - 2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=0.0.0.0:2888:3888
    entrypoint: |
      bash -c '
        /docker-entrypoint.sh zkServer.sh start-foreground'
    depends_on:
      - zookeeper-1
      - zookeeper-2
  zookeeper-init:
    image: zookeeper
    restart: on-failure
    hostname: zookeeper-init
    volumes:
      - "./zookeeper-init/remote_servers.xml:/remote_servers.xml"
      - "./zookeeper-init/quotas.xml:/quotas.xml"
      - "./zookeeper-init/profiles.xml:/profiles.xml"
      - "./zookeeper-init/users.xml:/users.xml"
      - "./zookeeper-init/users_all.xml:/users_all.xml"
      - "./zookeeper-init/compression.xml:/compression.xml"
      - "./zookeeper-init/graphite.xml:/graphite.xml"
      - "./zookeeper-init/graphite_rollup.xml:/graphite_rollup.xml"
      - "./zookeeper-init/clickhouse_zoo_config.sh:/clickhouse_zoo_config.sh"
    environment:
      - CLICKHOUSE_CONFIGS=remote_servers users_all compression graphite graphite_rollup
    entrypoint: |
      bash -c '
        sleep 30
        /clickhouse_zoo_config.sh'
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
  clickhouse-server-1:
    build:
      context: ./clickhouse-server
    restart: on-failure
    depends_on:
      - zookeeper-3
    volumes:
      - ./clickhouse-server/config.xml:/etc/clickhouse-server/config.xml
    privileged: true
    expose:
      - 9000
      - 8123
  clickhouse-server-2:
    build:
      context: ./clickhouse-server
    restart: on-failure
    depends_on:
      - clickhouse-server-1
    volumes:
      - ./clickhouse-server/config.xml:/etc/clickhouse-server/config.xml
    privileged: true
    expose:
      - 9000
      - 8123
  clickhouse-server-3:
    build:
      context: ./clickhouse-server
    restart: on-failure
    depends_on:
      - clickhouse-server-2
    volumes:
      - ./clickhouse-server/config.xml:/etc/clickhouse-server/config.xml
    privileged: true
    expose:
      - 9000
      - 8123
  clickhouse-server-4:
    build:
      context: ./clickhouse-server
    restart: on-failure
    depends_on:
      - clickhouse-server-3
    volumes:
      - ./clickhouse-server/config.xml:/etc/clickhouse-server/config.xml
    privileged: true
    expose:
      - 9000
      - 8123
  clickhouse-init:
    build:
      context: ./clickhouse-init
    restart: on-failure
    depends_on:
      - clickhouse-server-4
    volumes:
      - "./clickhouse-init/init_local_tables.sql.tpl:/init_local_tables.sql.tpl"
      - "./clickhouse-init/init_distributed_tables.sql:/init_distributed_tables.sql"
      - "./clickhouse-init/create_database.sql.tpl:/create_database.sql.tpl"
      - "./clickhouse-init/clickhouse-db-init.sh:/clickhouse-db-init.sh"
    environment:
      - CLICKHOUSE_CONFIGS=remote_servers users_all compression graphite graphite_rollup 
    entrypoint: |
      bash -c '
        sleep 120
        /clickhouse-db-init.sh'
  carbon-clickhouse-1:
    build:
      context: ./carbon-clickhouse
    volumes:
      - ./carbon-clickhouse/shard-1-config.conf:/etc/carbon-clickhouse/config.conf
    depends_on:
      - clickhouse-init
    expose:
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 7007
  carbon-clickhouse-2:
    build:
      context: ./carbon-clickhouse
    volumes:
      - ./carbon-clickhouse/shard-2-config.conf:/etc/carbon-clickhouse/config.conf
    depends_on:
      - clickhouse-init
    expose:
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 7007
  carbon-clickhouse-3:
    build:
      context: ./carbon-clickhouse
    volumes:
      - ./carbon-clickhouse/shard-3-config.conf:/etc/carbon-clickhouse/config.conf
    depends_on:
      - clickhouse-init
    expose:
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 7007
  carbon-clickhouse-4:
    build:
      context: ./carbon-clickhouse
    volumes:
      - ./carbon-clickhouse/shard-4-config.conf:/etc/carbon-clickhouse/config.conf
    depends_on:
      - clickhouse-init
    expose:
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 7007
  metrics-haproxy:
    image: haproxy
    hostname: metrics-haproxy
    volumes:
      - ./metrics-haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 2003:2003
      - 2004:2004
      - 2005:2005
      - 2006:2006
      - 2007:2007
      - 7007:7003
    expose:
      - 2003
    depends_on:
      - carbon-clickhouse-4
