version: '3.7'
services:
  zookeeper-1:
    image: zookeeper
    restart: always
    hostname: zookeeper-1
    ports:
      - 2181
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - "./zookeeper/remote_servers.xml:/remote_servers.xml"
      - "./zookeeper/clickhouse_zoo_config.sh:/clickhouse_zoo_config.sh"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
    entrypoint: |
      bash -c '
        /docker-entrypoint.sh zkServer.sh start
        sleep 45
        /clickhouse_zoo_config.sh'
  zookeeper-2:
    image: zookeeper
    restart: always
    hostname: zookeeper-2
#    logging:
#      driver: "none"
    ports:
      - 2182:2181
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - "./zookeeper/remote_servers.xml:/remote_servers.xml"
      - "./zookeeper/clickhouse_zoo_config.sh:/clickhouse_zoo_config.sh"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper-3:2888:3888
    entrypoint: |
      bash -c '
        /docker-entrypoint.sh zkServer.sh start-foreground
        sleep 60
        /clickhouse_zoo_config.sh'
    depends_on:
      - zookeeper-1
  zookeeper-3:
    image: zookeeper
    restart: always
    hostname: zookeeper-3
#    logging:
#      driver: "none"
    ports:
      - 2183:2181
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - "./zookeeper/remote_servers.xml:/remote_servers.xml"
      - "./zookeeper/clickhouse_zoo_config.sh:/clickhouse_zoo_config.sh"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=0.0.0.0:2888:3888
    entrypoint: |
      bash -c '
        /docker-entrypoint.sh zkServer.sh start-foreground
        sleep 75
        /clickhouse_zoo_config.sh'
    depends_on:
      - zookeeper-1
      - zookeeper-2
  clickhouse-server-1:
    build:
      context: ./clickhouse-server
    depends_on:
      - zookeeper-3
    volumes:
      - ./clickhouse-server/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-server/rollup.xml:/etc/clickhouse-server/config.d/rollup.xml
    privileged: true
    expose:
      - 9000
      - 8123
  clickhouse-server-2:
    build:
      context: ./clickhouse-server
    depends_on:
      - clickhouse-server-1
    volumes:
      - ./clickhouse-server/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-server/rollup.xml:/etc/clickhouse-server/config.d/rollup.xml
    privileged: true
    expose:
      - 9000
      - 8123
  clickhouse-server-3:
    build:
      context: ./clickhouse-server
    depends_on:
      - clickhouse-server-2
    volumes:
      - ./clickhouse-server/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-server/rollup.xml:/etc/clickhouse-server/config.d/rollup.xml
    privileged: true
    expose:
      - 9000
      - 8123
  clickhouse-server-4:
    build:
      context: ./clickhouse-server
    depends_on:
      - clickhouse-server-3
    volumes:
      - ./clickhouse-server/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-server/rollup.xml:/etc/clickhouse-server/config.d/rollup.xml
    privileged: true
    expose:
      - 9000
      - 8123
  carbon-clickhouse-1:
    build:
      context: ./carbon-clickhouse
    volumes:
      - ./carbon-clickhouse/shard-1-config.conf:/etc/carbon-clickhouse/config.conf
      - ./carbon-clickhouse/data:/data/carbon-clickhouse/
    depends_on:
      - clickhouse-server-4
    expose:
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 7007
  carbon-clickhouse-2:
    build:
      context: ./carbon-clickhouse
    volumes:
      - ./carbon-clickhouse/shard-1-config.conf:/etc/carbon-clickhouse/config.conf
      - ./carbon-clickhouse/data:/data/carbon-clickhouse/
    depends_on:
      - clickhouse-server-4
    expose:
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 7007
#clickhouse-init:
#    build:
#      context: ./clickhouse-init
#    depends_on:
#      - clickhouse-server-4
#    volumes:
#      - "./clickhouse-init/init_local_tables_1.sql:/init_local_tables_1.sql"
#      - "./clickhouse-init/init_local_tables_2.sql:/init_local_tables_2.sql"
#      - "./clickhouse-init/init_local_tables_3.sql:/init_local_tables_3.sql"
#      - "./clickhouse-init/init_local_tables_4.sql:/init_local_tables_4.sql"
#      - "./clickhouse-init/init_distributed_tables.sql:/init_distributed_tables.sql"
#      - "./clickhouse-init/create-database.sql:/create-database.sql"
#    entrypoint: |
#      bash -c '
#        sleep 2
#        export HOME=/var/lib/clickhouse/
#        cat /create-database.sql | clickhouse client --host clickhouse-server-1 --multiquery
#        cat /create-database.sql | clickhouse client --host clickhouse-server-2 --multiquery
#        cat /create-database.sql | clickhouse client --host clickhouse-server-3 --multiquery
#        cat /create-database.sql | clickhouse client --host clickhouse-server-4 --multiquery
#        cat /init_local_tables_1.sql | clickhouse client --host clickhouse-server-1 --multiquery
#        cat /init_local_tables_2.sql | clickhouse client --host clickhouse-server-2 --multiquery
#        cat /init_local_tables_3.sql | clickhouse client --host clickhouse-server-3 --multiquery
#        cat /init_local_tables_4.sql | clickhouse client --host clickhouse-server-4 --multiquery
#        cat /init_distributed_tables.sql | clickhouse client --host clickhouse-server-1 --database default --multiquery
#        cat /init_distributed_tables.sql | clickhouse client --host clickhouse-server-2 --database default --multiquery
#        cat /init_distributed_tables.sql | clickhouse client --host clickhouse-server-3 --database default --multiquery
#        cat /init_distributed_tables.sql | clickhouse client --host clickhouse-server-4 --database default --multiquery'
  carbon-clickhouse-3:
    build:
      context: ./carbon-clickhouse
    volumes:
      - ./carbon-clickhouse/shard-2-config.conf:/etc/carbon-clickhouse/config.conf
      - ./carbon-clickhouse/data:/data/carbon-clickhouse/
    depends_on:
      - clickhouse-server-4
    expose:
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 7007
  carbon-clickhouse-4:
    build:
      context: ./carbon-clickhouse
    volumes:
      - ./carbon-clickhouse/shard-2-config.conf:/etc/carbon-clickhouse/config.conf
      - ./carbon-clickhouse/data:/data/carbon-clickhouse/
    depends_on:
      - clickhouse-server-4
    expose:
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 7007
  metrics-haproxy:
    image: haproxy
    hostname: metrics-haproxy
    volumes:
      - ./metrics-haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 2003:2003
      - 2004:2004
      - 2005:2005
      - 2006:2006
      - 2007:2007
      - 7007:7003
    depends_on:
      - carbon-clickhouse-1
